rate: 50
# Homogeneous coordinates : see e.g. p17 www.ensta-bretagne.fr/lebars/Obs_et_filt_de_Kalman.pdf
angular_transform_matrix: [  1,  0,  0,  0,
                             0,  1,  0,  0,
                             0,  0,  1,  0,
                             0,  0,  0,  1]
linear_transform_matrix: [  1,  0,  0,  0,
                            0,  1,  0,  0,
                            0,  0,  1,  0,
                            0,  0,  0,  1]
subscriber:
  topic: "/twist"
  queue: 1000
publisher:
  topic: "/cmd_vel"
  queue: 1000
