cmd_vel:
  topic: "/cmd_vel"
imu:
  topic: "/imu/data"
fix:
  topic: "/navsat/fix"
vel:
  topic: "/vel"
bOverrideFixStatus: true
max_linear_x_speed: 4.0
max_angular_z_speed: 4.0
szVectorNavInterfacePath: "127.0.0.1:5765"
